apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    app: website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      nodeSelector:
        devday: awesome
      containers:
      - name: games-website
        image: stevearacom/website
        ports:
        - containerPort: 3000
