{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name:  {{ template "fullname" . }}
spec:
  selector:
    app: {{ .Values.pod.labels.app }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.container.port }}
{{- end -}}
