{{- if .Values.configmap.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configmap.name }}
data:
  {{- with .Values.configmap.data }}
  {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end -}}
