apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: website
  name: website
  labels:
    app: website-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: games-website
        image: stevearacom/website:alpha
        ports:
        - containerPort: 3000
