apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend
spec:
  type: NodePort
  selector:
    app: simple-backend
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30007
